version: '3'

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        env_file: .dev.env
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node/app
            - ./node_modules:/home/node/app/node_modules
        command: npm run dev
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'guilherme'
            MYSQL_PASSWORD: 'admin'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./database:/var/lib/mysql
            - ./db:/dev/stock_manager